### ISSUE TITLE
Gives false positive error on set_facts

### ISSUE THREAD

**Issue by JakkuSakura** [VSChina/vsc-extension-ansible#286]
## Reproduce steps
I have
```yaml
- name: Set asg_properties variable from JSON output if the Auto Scaling Group already exists
  set_fact:
    asg_properties: "{{ (asg_properties_result.stdout | from_json).AutoScalingGroups[0] }}"
  when: (asg_properties_result.stdout | from_json).AutoScalingGroups | count

```

## Expected Results
No warnings

## Actual Results
![image](https://user-images.githubusercontent.com/33482468/110194521-8f924a00-7e73-11eb-9035-334a739474ed.png)
Says missing property key_value. The key_value is not an actual key_value and there is no need to gives an error
